export const articleData = [
  {
    title: "Exercise",
    head: "Exercise",
    body: "The positive influence of exercise on mood and cognition across the lifespan has become a topic of much excitement . In particular, abundant data suggest that physical activity can reduce the risk of various neurological diseases and protect the brain from the detrimental effects of aging . Animal models have focused mainly on the effects of long-term exercise (i.e., weeks to months of increased exercise) on hippocampal function, with special emphasis on exercise-induced adult hippocampal neurogenesis and hippocampal-dependent learning and memory . Studies in rodents have also documented the neuroanatomical, neurochemical, and cellular/molecular changes associated with long-term exposure to exercise . In humans, both behavioral and functional imaging approaches have started to identify the neuroanatomical systems modulated by long-term increases in exercise. The most commonly reported area to undergo improvement is the prefrontal cortex, with exercise-induced enhancements observed in attention and other executive functions [9]. As well as for improving cognition in children and healthy adults, these long-term effects of exercise are of particular interest for their possible role in improving cognitive function during aging . As we age, cognitive decline, though not inevitable, is a common occurrence resulting from the process of neurodegeneration. In some instances, neurodegeneration results in mild cognitive impairment or more severe forms of dementia including Alzheimer’s, Parkinson’s, or Huntington’s disease. Because of the role of exercise in enhancing neurogenesis and brain plasticity, physical activity may serve as a potential therapeutic tool to prevent, delay, or treat cognitive decline. Indeed, studies in both rodents and humans have shown that long-term exercise is helpful in both delaying the onset of cognitive decline and dementia as well as improving symptoms in patients with an already existing diagnosis .",
  },
  {
    title: "Sleep",
    head: "Sleep",
    body: "Why do we need to sleep? People often think that sleep is just “down time,” when a tired brain gets to rest, says Dr. Maiken Nedergaard, who studies sleep at the University of Rochester.“But that’s wrong,” she says. While you sleep, your brain is working. For example, sleep helps prepare your brain to learn, remember, and create. Nedergaard and her colleagues discovered that the brain has a drainage system that removes toxins during sleep.“When we sleep, the brain totally changes function,” she explains. “It becomes almost like a kidney, removing waste from the system.”Her team found in mice that the drainage system removes some of the proteins linked with Alzheimer’s disease. These toxins were removed twice as fast from the brain during sleep.Everything from blood vessels to the immune system uses sleep as a time for repair, says Dr. Kenneth Wright, Jr., a sleep researcher at the University of Colorado.“There are certain repair processes that occur in the body mostly, or most effectively, during sleep,” he explains. “If you don’t get enough sleep, those processes are going to be disturbed.”",
  },
  {
    title: "Food",
    head: "Food",
    body: "As people across the globe grappled with higher levels of stress, depression and anxiety this past year, many turned to their favorite comfort foods: ice cream, pastries, pizza, hamburgers. But studies in recent years suggest that the sugar-laden and high-fat foods we often crave when we are stressed or depressed, as comforting as they may seem, are the least likely to benefit our mental health. Instead, whole foods such as vegetables, fruit, fish, eggs, nuts and seeds, beans and legumes and fermented foods like yogurt may be a better bet.The findings stem from an emerging field of research known as nutritional psychiatry, which looks at the relationship between diet and mental wellness. The idea that eating certain foods could promote brain health, much the way it can promote heart health, might seem like common sense. But historically, nutrition research has focused largely on how the foods we eat affect our physical health, rather than our mental health. For a long time, the potential influence of food on happiness and mental well-being, as one team of researchers recently put it, was “virtually ignored.”But over the years, a growing body of research has provided intriguing hints about the ways in which foods may affect our moods. A healthy diet promotes a healthy gut, which communicates with the brain through what is known as the gut-brain axis. Microbes in the gut produce neurotransmitters like serotonin and dopamine, which regulate our mood and emotions, and the gut microbiome has been implicated in mental health outcomes. “A growing body of literature shows that the gut microbiome plays a shaping role in a variety of psychiatric disorders, including major depressive disorder,” a team of scientists wrote in the Harvard Review of Psychiatry last year.Large population studies, too, have found that people who eat a lot of nutrient-dense foods report less depression and greater levels of happiness and mental well-being. One such study, from 2016, that followed 12,400 people for about seven years found that those who increased their consumption of fruits and vegetables during the study period rated themselves substantially higher on questionnaires about their general levels of happiness and life satisfaction.",
  },
  {
    title: "Love",
    head: "Love",
    body: "Love is the most essential element of every being, and it is the most radiant light, and it is the greatest power; able to resist and overcome all else. Love elevates every soul that absorbs it, and prepares these souls for the journey to eternity. Souls that have been able to make contact with eternity through love exert themselves to inspire in all other souls what they have derived from eternity. They dedicate their lives to this sacred duty; a duty for the sake of which they endure every kind of hardship to the very end, and just as they pronounce love with their last breath, they will also breathe love while being raised on the Day of Judgment.It is impossible for souls without love to be elevated to the horizon of human perfection. Even if they lived for hundreds of years, they could not advance on the path to perfection. Those who are deprived of love, as they are entangled in the nets of selfishness, are unable to love anybody else and die unaware of the love that is deeply instilled in the very being of existence.There are impressions of love on the face of the sun; water evaporates, rising toward those impressions, and after it has been condensed in drops high above, the drops fall joyfully onto the earth on wings of love. Then, thousands of flowers burst through with love, offering smiles to their surroundings. Dew drops on leaves glitter with love and twinkle with amusement. Sheep and lambs bleat and skip about with love, and birds and chicks chirp with love and form choruses of love.Each being takes part in the grand orchestra of love in the universe with its own particular symphony and tries to demonstrate, by free will or through its disposition, an aspect of the deep love that is found in existence.Love is ingrained in the soul of a human being so deeply that many people leave their home for its sake, many families are ruined, and, in every corner, a Majnun groans with love, longing for his Layla. As for those who have not been able to uncover the love inherent in their being, they regard such manifestations of love as madness!Altruism is an exalted human feeling, and its source is love. Whoever has the greatest share in this love is the greatest hero of humanity; these people have been able to uproot any feelings of hatred and rancor in themselves. Such heroes of love continue to live even after their death. These lofty souls who, by each day kindling a new torch of love in their inner world and by making their hearts a source of love and altruism, are welcomed and loved by people, have received the right to an eternal life from the Supreme Judge. Death, not even Doomsday, will be able to remove their traces.",
  },
];
